CREATE TABLE public.katu as (
SELECT 
    id,
    addinfo1,
    addinfo1text,
    addinfo2,
    addinfo2text,
    completionyear,
    label,
    maintainedby,
    maintainedbytext,
    maintenanceclass,
    maintenanceclasstext,
    name,
    owner,
    ownertext,
    partclass,
    partclasstext,
    partnumber,
    pavingclass as pavingmaterial,
    pavingclasstext as pavingmaterialtext,
    possessor,
    possessortext,
    registerstate,
    registerstatetext,
    repairyear,
    status,
    statustext,
    usetype,
    usetypetext,
    wintermaintenance,
    geom
    FROM katuindex
);


CREATE TABLE public.viher as (
SELECT 
    id,
    addinfo1,
    addinfo1text,
    addinfo2,
    addinfo2text,
    completionyear,
    label,
    maintainedby,
    maintainedbytext,
    maintenanceclass,
    maintenanceclasstext,
    name,
    owner,
    ownertext,
    partclass,
    partclasstext,
    partnumber,
    pavingmaterial,
    pavingmaterialtext,
    possessor,
    possessortext,
    registerstate,
    registerstatetext,
    repairyear,
    status,
    statustext,
    usetype,
    usetypetext,
    wintermaintenance,
    geom
    FROM viherindex
);